baseURL = 'https://pedromiguelmb.com'
languageCode = 'en-EN'
copyright = 'Pedro Barreiro'
title = 'Pedro Barreiro'
theme = 'hugo-theme-stack'
paginate = 15

[params]
  favicon = "/about_me.svg"

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/pedro-barreiro.jpeg"

[menu]
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/pedrommb91"
    [menu.social.params]
      icon = "brand-github"
  [[menu.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/pedro-barreiro-b0117967/"
    [menu.social.params]
      icon = "brand-linkedin"

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
      icon = "home"
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 2
    [menu.main.params]
      icon = "about_me"
